spring.application.name=sb-ecom-wolf

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

project.image=images/

# Propriedades para ver e entender as queries que o Hibernate gera e executa.
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Para logar as requisições HTTP e respostas.
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
# logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
# logging.level.org.apache.catalina.core=DEBUG